# Generated by Django 5.0.1 on 2024-03-09 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessowner",
            name="business_name",
        ),
    ]
