# Generated by Django 5.0.1 on 2024-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_businessowner_business_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessowner",
            name="business_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="first_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="last_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
