# Generated by Django 5.0.1 on 2024-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default-4.jpg", upload_to="profile_pics"),
        ),
    ]
