# Generated by Django 5.0 on 2024-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_verificationcodecustomer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcodecustomer",
            name="time",
        ),
        migrations.AddField(
            model_name="verificationcodecustomer",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
