# Generated by Django 5.0 on 2024-04-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_verificationcodecustomer_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCodeBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.UUIDField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.business",
                    ),
                ),
            ],
        ),
    ]
