# Generated by Django 4.2.10 on 2024-06-26 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_chat_user1_alter_chat_user2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="user2",
            new_name="the_business",
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="user1",
            new_name="the_customer",
        ),
    ]
