# Generated by Django 5.0 on 2024-04-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_remove_verificationcodebusiness_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcodebusiness",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.business",
            ),
        ),
    ]
