# Generated by Django 5.0 on 2024-04-19 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_verificationcodebusiness_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcodecustomer",
            name="customer",
        ),
        migrations.DeleteModel(
            name="VerificationCodeBusiness",
        ),
        migrations.DeleteModel(
            name="VerificationCodeCustomer",
        ),
    ]
