# Generated by Django 4.2.10 on 2024-07-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_message_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
