# Generated by Django 5.0 on 2024-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_remove_verificationcodecustomer_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
