# Generated by Django 5.0.1 on 2024-03-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_businessowner_business_name_and_more"),
        ("shop", "0002_alter_order_customer_alter_shippingaddress_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.businessowner",
            ),
        ),
    ]
