# Generated by Django 5.0.1 on 2024-03-12 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_category_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="product_category",
        ),
    ]
