# Generated by Django 5.0.1 on 2024-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_rename_category_product_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
