# Generated by Django 5.0.1 on 2024-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
