# Generated by Django 5.0.1 on 2024-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
