# Generated by Django 5.0.1 on 2024-03-12 17:14

import shop.utilities
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=shop.utilities.rename_image
            ),
        ),
    ]
