# Generated by Django 5.0.1 on 2024-03-12 17:21

import shop.utilities
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=shop.utilities.rename_image,
            ),
        ),
    ]
