# Generated by Django 5.0.1 on 2024-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
